export const cars =
  [
    {
      id: 1,
      'image': 'https://api2.ma.ru/images/models/toyota/camry/28652/28652_medium.jpg',
      'brand': 'Toyota',
      'model': 'Camry',
      'price': 30000,
      'year': 2022,
      'color': 'Blue',
      'engine_type': 'Petrol',
      'transmission': 'Automatic',
      'mileage': null,
      'equipment': ['adjustable_seats', 'cruise_control', 'air_conditioning'],
    },
    {
      id: 2,
      'image': 'https://www.aoyama.ru/pix/auto/accord/accord_1400.png',
      'brand': 'Honda',
      'model': 'Accord',
      'price': 28000,
      'year': 2023,
      'color': 'Silver',
      'engine_type': 'Petrol',
      'transmission': 'Manual',
      'mileage': null,
      'equipment': ['adjustable_steering', 'central_lock', 'immobilizer'],
    },
    {
      id: 3,
      'image': 'https://moscowteslaclub.ru/upload/resize_cache/iblock/924/1266_715_2/ncvli6itlfabjgn42vtlqbn0btjzb8tr.jpg',
      'brand': 'Tesla',
      'model': 'Model S',
      'price': 80000,
      'year': 2022,
      'color': 'Black',
      'engine_type': 'Electric',
      'transmission': null,
      'mileage': 500,
      'equipment': ['heated_steering', 'heated_seats', 'rear_camera', 'climate_control'],
    },
    {
      id: 4,
      'image': 'https://autopremiumgroup.ru/m/_versions/catalog/autos/2022/ford_mustang_2022_kupe/mach_1/2022_mustang_mach_1_sb_1_image_series.jpg',
      'brand': 'Ford',
      'model': 'Mustang',
      'price': 45000,
      'year': 2023,
      'color': 'Red',
      'engine_type': 'Petrol',
      'transmission': 'Automatic',
      'mileage': null,
      'equipment': ['power_windows', 'central_lock', 'air_conditioning'],
    },
    {
      id: 5,
      'image': 'https://s.auto.drom.ru/i24220/m/bull_image_stub/default_a73cc4559868188c70b0d81a79c2a9a8.jpg',
      'brand': 'Chevrolet',
      'model': 'Camaro',
      'price': 48000,
      'year': 2022,
      'color': 'Yellow',
      'engine_type': 'Petrol',
      'transmission': 'Manual',
      'mileage': null,
      'equipment': ['power_steering', 'cruise_control', 'immobilizer'],
    },
    {
      id: 6,
      'image': 'https://cdn.wheel-size.com/automobile/body/nissan-altima-2019-2022-1628848253.0533092.jpg',
      'brand': 'Nissan',
      'model': 'Altima',
      'price': 32000,
      'year': 2023,
      'color': 'White',
      'engine_type': 'Electric',
      'transmission': null,
      'mileage': 450,
      'equipment': ['heated_seats', 'rear_camera', 'climate_control'],
    },
    {
      id: 7,
      'image': 'https://www.bmwhk.com/content/dam/bmw/common/all-models/3-series/sedan/2018/inform/bmw-3series-3er-inform-lines-02-01.jpg.asset.1624549612346.jpg',
      'brand': 'BMW',
      'model': '3 Series',
      'price': 55000,
      'year': 2022,
      'color': 'Gray',
      'engine_type': 'Petrol',
      'transmission': 'Automatic',
      'mileage': null,
      'equipment': ['power_windows', 'power_seats', 'air_conditioning'],
    },
    {
      id: 8,
      'image': 'https://tdc-prod.ams3.digitaloceanspaces.com/c175db1f-42e7-4a81-b46b-a6c20a3e5518.jpg',
      'brand': 'Audi',
      'model': 'A4',
      'price': 52000,
      'year': 2023,
      'color': 'Silver',
      'engine_type': 'Diesel',
      'transmission': 'Automatic',
      'mileage': null,
      'equipment': ['power_steering', 'central_lock', 'cruise_control'],
    },
    {
      id: 9,
      'image': 'https://edgecast-img.yahoo.net/mysterio/api/D9EE9D9F9FF42A75B0EFF69036F0A5BD9456961633D1EC321F99F5BD531433A9/autoblog/resizefill_w660_h372;quality_80;format_webp;cc_31536000;/https://s.aolcdn.com/commerce/autodata/images/USD20MBC891A021001.jpg',
      'brand': 'Mercedes-Benz',
      'model': 'C-Class',
      'price': 60000,
      'year': 2022,
      'color': 'Black',
      'engine_type': 'Diesel',
      'transmission': 'Automatic',
      'mileage': null,
      'equipment': ['power_windows', 'power_seats', 'climate_control'],
    },
    {
      id: 10,
      'image': 'https://p.turbosquid.com/ts-thumb/SX/P7EwcY/HkDEoejD/volkswagen_passat_variant_gte_2020_0000/jpg/1602753325/600x600/fit_q87/60686a3898424d9c45afb6b1ed111a29f966142e/volkswagen_passat_variant_gte_2020_0000.jpg',
      'brand': 'Volkswagen',
      'model': 'Passat',
      'price': 35000,
      'year': 2023,
      'color': 'Blue',
      'engine_type': 'Petrol',
      'transmission': 'Manual',
      'mileage': null,
      'equipment': ['central_lock', 'immobilizer', 'cruise_control'],
    },
  ];
